name: Deploy-Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Trunk
      run: 
        curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
        && cargo binstall --locked trunk
        && rustup target add wasm32-unknown-unknown
    - name: Build
      run: trunk build
    - name: Tar
      run: tar -czvf github-pages dist/ 
      
  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write
      
    steps:
      - uses: actions/deploy-pages@v4.0.5
