name: Deploy-Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: cargo-bins/cargo-binstall@main
    - name: Install Trunk
      run: 
        cargo binstall --no-confirm --locked trunk
        && rustup target add wasm32-unknown-unknown
    - name: Build
      run: trunk build
    - name: Tar
      run: tar -czvf github-pages dist/ 
      
  deploy:
    runs-on: ubuntu-latest

    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

      
    steps:
      - run: echo $(ls)
      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3

      - uses: actions/deploy-pages@v4.0.5
        id: deployment

